package yzh.stock.business.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("album")
public class Album {
    @TableId(type = IdType.AUTO)
    private Long id;
    private Long userId;
    private String albumName;
    private String description;
    private Long coverPhotoId;
    private Integer autoGenerated;
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;
}
